name: ASP.NET Core CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build & Test with dotnet
      run: | 
        dotnet build src/Onff.sln --configuration Release
        dotnet test src/Onff.sln --configuration Release 
    - name: Publish sucess to Microsoft Teams
      uses: moattarwork/Action.Teams.SendMessage@master
      with:
        webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }
        message: 'Build was successful for Onff project'
